### ISSUE TITLE
Include proper documentation

### ISSUE THREAD

**Issue by AaravMalani** [AaravMalani/libjson#1]
The options are either
- Create a Github Wiki page
- Include in the `README.md` file (preferred)
- Include in another Markdown file
- Host it on a separate website (like Github Pages)

**Comment by proh14** [comment]
Hello @AaravMalani I would like to work on this from the third option (Include in another ...)

**Comment by AaravMalani** [comment]
@proh14 made a PR, therefore this issue is resolved.
